language: node_js

services:
  - docker

install:
  - docker build -t smash-league .

script:
      - docker run --rm smash-league npm test
      - docker run --rm -v ${TRAVIS_BUILD_DIR}/ranking-info:/usr/app/ranking-info -e SLACK_API_TOKEN=${SLACK_API_TOKEN} smash-league

if: commit_message =~ /^(?!Deploy .* to .*\:.*).+/ OR type IN (cron, api)

deploy:
  - provider: pages
    target-branch: $TRAVIS_BRANCH
    skip-cleanup: true
    github-token: $GITHUB_OAUTH_TOKEN
    keep-history: true
    local-dir: $TRAVIS_BUILD_DIR
    varbose: true
    on:
      branch: master
      