language: node_js

services:
  - docker

install:
  - docker build -t smash-league .

stages:
  - name: Test
    script:
      - docker run --rm -v ${TRAVIS_BUILD_DIR}/ranking-info:/usr/app/ranking-info -e SLACK_API_TOKEN=${SLACK_API_TOKEN} smash-league npm test
  - name: Build
    script:
      - docker run --rm -v ${TRAVIS_BUILD_DIR}/ranking-info:/usr/app/ranking-info -e SLACK_API_TOKEN=${SLACK_API_TOKEN} smash-league

deploy:
  - provider: pages
    target-branch: $TRAVIS_BRANCH
    skip-cleanup: true
    github-token: $GITHUB_OAUTH_TOKEN
    keep-history: true
    local-dir: $TRAVIS_BUILD_DIR
    varbose: true
    on:
      all_branches: true
      condition: $TRAVIS_EVENT_TYPE = cron OR $TRAVIS_EVENT_TYPE = api
      